org.gradle.jvmargs=-Xmx1024M -XX:MaxMetaspaceSize=384M -XX:ReservedCodeCacheSize=192M -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
